In [6]:
import numpy as np
a = np.array([1,2,3,4])#create an array
print(a)

print(np.arange(10))


[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
!pip install numpy


     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.9 kB 640.0 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 650.2 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 649.9 kB/s eta 0:00:00
   ---------------------------------------- 0.0/13.1 MB ? eta -:--:--
    --------------------------------------- 0.2/13.1 MB 3.5 MB/s eta 0:00:04
   -- ------------------------------------- 0.7/13.1 MB 8.7 MB/s eta 0:00:02
   ------- -------------------------------- 2.5/13.1 MB 20.2 MB/s eta 0:00:01
   ---------- ----------------------------- 3.6/13.1 MB 22.6 MB/s eta 0:00:01
   -------------- ------------------------- 4.8/13.1 MB 23.6 MB/s eta 0:00:01
   ----------------- ---------------------- 5.8/13.1 MB 26.3 MB/s eta 0:00:01
   -------------------- ------------------- 6.7/13.1 MB 25.3 MB/s eta 0:00:01
   -------------------- ------------------- 6.7/13.1 MB 25.3 MB/s eta 0:00


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: C:\Users\Shahal\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [7]:
L = range(1000)
square =[]
for i in range(1000):
    if i%2==0:
        square.append(i**2)
print(square)

[0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096, 4356, 4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396, 7744, 8100, 8464, 8836, 9216, 9604, 10000, 10404, 10816, 11236, 11664, 12100, 12544, 12996, 13456, 13924, 14400, 14884, 15376, 15876, 16384, 16900, 17424, 17956, 18496, 19044, 19600, 20164, 20736, 21316, 21904, 22500, 23104, 23716, 24336, 24964, 25600, 26244, 26896, 27556, 28224, 28900, 29584, 30276, 30976, 31684, 32400, 33124, 33856, 34596, 35344, 36100, 36864, 37636, 38416, 39204, 40000, 40804, 41616, 42436, 43264, 44100, 44944, 45796, 46656, 47524, 48400, 49284, 50176, 51076, 51984, 52900, 53824, 54756, 55696, 56644, 57600, 58564, 59536, 60516, 61504, 62500, 63504, 64516, 65536, 66564, 67600, 68644, 69696, 70756, 71824, 72900, 73984, 75076, 76176, 77284, 78400, 79524, 80656, 81796, 82944, 84100, 85264, 86436, 87616, 88804, 90000, 91204, 92416, 9

In [ ]:
square = [i**2 for i in L if i%2==0]#list comperhension
print(square)#to get time we use %timeit


[0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096, 4356, 4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396, 7744, 8100, 8464, 8836, 9216, 9604, 10000, 10404, 10816, 11236, 11664, 12100, 12544, 12996, 13456, 13924, 14400, 14884, 15376, 15876, 16384, 16900, 17424, 17956, 18496, 19044, 19600, 20164, 20736, 21316, 21904, 22500, 23104, 23716, 24336, 24964, 25600, 26244, 26896, 27556, 28224, 28900, 29584, 30276, 30976, 31684, 32400, 33124, 33856, 34596, 35344, 36100, 36864, 37636, 38416, 39204, 40000, 40804, 41616, 42436, 43264, 44100, 44944, 45796, 46656, 47524, 48400, 49284, 50176, 51076, 51984, 52900, 53824, 54756, 55696, 56644, 57600, 58564, 59536, 60516, 61504, 62500, 63504, 64516, 65536, 66564, 67600, 68644, 69696, 70756, 71824, 72900, 73984, 75076, 76176, 77284, 78400, 79524, 80656, 81796, 82944, 84100, 85264, 86436, 87616, 88804, 90000, 91204, 92416, 9

In [ ]:

name =[1,2,3,4]
a =[print(name(i) for i in name)]#solve this and clear the way 

<generator object <genexpr> at 0x0000021B13BA52A0>


## 1 dimensional array


In [13]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [14]:
a.ndim #for understand which dimension of the array

1

In [15]:
a.shape#to understand the array's shape (its important)

(4,)

In [22]:
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)
a.shape

2


(2, 3)

In [26]:
a = np.array([[[2,3],[3,5]],[[45,67],[100,200]]])
print(a)
print(a.ndim)
a.shape

[[[  2   3]
  [  3   5]]

 [[ 45  67]
  [100 200]]]
3


(2, 2, 2)

In [27]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b = np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])