In [1]:
import numpy as np


In [8]:
a = np.array([1,2,3,4])
print(a+3)
print(a**2)
print(a/2)
print(a-3)

[4 5 6 7]
[ 1  4  9 16]
[0.5 1.  1.5 2. ]
[-2 -1  0  1]


In [13]:
a = np.array([1,2,3,4],dtype="int")
b = np.array([5,6,7,8],dtype ="int")

print("addition is ",a+b)
print("subtraction is ",a-b)
print("mulitplication is ",a*b)
print("division is ",b/a)

addition is  [ 6  8 10 12]
subtraction is  [-4 -4 -4 -4]
mulitplication is  [ 5 12 21 32]
division is  [5.         3.         2.33333333 2.        ]


In [25]:
a = np.arange(10)
print(a)
b = a[::2]
print(b)
np.shares_memory(a,b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


True

In [30]:
b[1]=111
print(a)
print(b)
np.shares_memory(a,b)

[  0   1 111   3   4   5   6   7   8   9]
[  0 111   4   6   8]


True

In [34]:
a = np.array([0,1,2,3,4,5,6,7])
c = np.copy(a[3:7])
np.shares_memory(a,c)

False

In [40]:
mask = (a%2==0)
b = a[mask]
print(a[mask])


[0 2 4 6]


In [42]:
a = np.arange(0,100,10)
a[[2,3,2,5]]=100
a


array([  0,  10, 100, 100,  40, 100,  60,  70,  80,  90])

In [8]:
import numpy as np
b = np.ones(3,dtype="int")+1
a = np.ones(3)+3
print(a)
print(b)
a*b

[4. 4. 4.]
[2 2 2]


array([8., 8., 8.])

In [13]:
c = np.diag([1,2,3,4])

print(c*c)
print("******************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
******************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [17]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
print(np.dot(a,b))

300


In [ ]:
a = np.array([1,2,3,4])
b = np.array([1,2,5,5])
print(a==b)
print(a>b)

array([ True,  True, False, False])